

--1

SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE; 


--2

SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


--3
-- 춘 기술대학교의 남자 교수들의 이름과 나이를 출력하는 SQL 문장을 작성하시오.
-- 단 이 때 나이가 적은 사람에서 많은 사람 순서로 화면에 출력되도록 만드시오.
-- (단, 교수 중 2000년 이후 출생자는 없으며 출력 헤더는 "교수이름"으로 한다. 나이는 '만'으로 계산한다.)
SELECT PROFESSOR_NAME AS 교수이름, PROFESSOR_SSN , TRUNC(MONTHS_BETWEEN(SYSDATE ,TO_DATE('19' || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD'))/12) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;


--4

SELECT SUBSTR(PROFESSOR_NAME,2,2) 이름
FROM TB_PROFESSOR;


--5
-- 춘 기술대학교의 재수생 입학자를 구하려고 한다 어떻게 찾아낼 거인가?
-- 이때, 19살에 입학하면 재수를 하지 않은 것으로 간주한다.

SELECT STUDENT_NO , STUDENT_SSN , ENTRANCE_DATE , STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE('19' || SUBSTR(STUDENT_SSN, 1, 6) ,'YYYYMMDD')) > 19;


--6
SELECT TO_CHAR(TO_DATE(20201225,'YYMMDD'), 'DAY') 크리스마스
FROM DUAL;

SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY') 크리스마스
FROM DUAL;

--7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY') , TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY')
FROM DUAL; -- 2099-10-11 / 2049-10-11

SELECT TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'),'RRRR') , TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'),'RRRR')
FROM DUAL; --1999-10-11 / 2049-10-11

-- YY는 모두 2000년대
-- RR은 49이하는 2000년대 50이상은 1900년대

--8

SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000; 
--WHERE STUDENT_NO NOT LIKE 'A%';

--9
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


--10

SELECT DEPARTMENT_NO 학과번호 , count(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;
 

--11

SELECT count(*)
FROM TB_STUDENT ts 
WHERE COACH_PROFESSOR_NO IS NULL;


--12
-- 학번이 A112113인 김고운 학생의 년도 별 평점을 구하는 SQL문을 작성하시오.
-- 단, 이때 출력화면의 헤더는 "년도", "년도 별 평점"이라고 찍히게 하고, 점수는 반올림하여 소수점 이하 한자리까지만 표시한다.
SELECT EXTRACT(YEAR FROM TO_DATE(TERM_NO,'YYMM')) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY EXTRACT(YEAR FROM TO_DATE(TERM_NO,'YYMM'))
ORDER BY 년도;

SELECT SUBSTR(TERM_NO,1,4) AS 연도, ROUND(AVG(POINT),1) AS "연도별 평점"  
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 연도;



--13
SELECT DEPARTMENT_NO 학과코드명, SUM(DECODE(ABSENCE_YN, 'Y', 1, 'N',0)) "휴학생 수"
--SELECT DEPARTMENT_NO "학과코드명", COUNT(DECODE(ABSENCE_YN,'Y','Y','NO',0))"휴학생 수"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO  
ORDER BY DEPARTMENT_NO ;

SUM(DECODE(ABSENCE_YN, 'Y', 1, 'N',0))


--14
-- 춘 대학교에 다니는 동명이인 학생들의 이름을 찾고자 한다.
-- 어떤 SQL 문장을 사용하면 가능하겠는가?

SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS "동명인 수" 
FROM TB_STUDENT
GROUP BY STUDENT_NAME 
HAVING COUNT(*) > 1
ORDER BY 동일이름;





-- 15
-- 학번이 A112113인 김고운 학생의 년도, 학기 별 평점과 년도 별 누적 평점, 총 평점을 구하는 SQL문을 작성하시오.
-- (단, 평점은 소수점 1자리까지만 반올림하여 표시한다.)

SELECT NVL(SUBSTR(TERM_NO,1,4), ' ') AS 년도, NVL(SUBSTR(TERM_NO,5,2),' ') AS 학기, ROUND(AVG(POINT),1) AS 평점  
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));




