-- 07_SUBQUERY_실습문제

-- 1. 전지연이 속해있는 부서원

SELECT EMP_ID , EMP_NAME , PHONE , HIRE_DATE , DEPT_TITLE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE
					FROM EMPLOYEE
					WHERE EMP_NAME = '전지연')
AND EMP_NAME <> '전지연'
ORDER BY EMP_ID ;


SELECT EMP_NAME , DEPT_CODE 
FROM EMPLOYEE
WHERE DEPT_CODE = 'D9';
